
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="stylesheet" href="/styles.css">
</head>

<body>
        <nav>   
                <a href="/">Home</a>
                <a href="/profile">Profile</a>
                <a href="/my-bookings">My Bookings</a>
                <a href="/providers">Services</a>
                <a href="/logout">Logout</a>

                
        </nav>

    
            <h1> CleanSweep</h1>
            <div class="intro">
                <p><strong>Welcome to CleanSweep!</strong></p>
                <p>Your one-stop solution for all your cleaning needs. Whether you're looking for a quick tidy-up or a deep clean, we've got you covered.</p>
                <p>Our platform connects you with trusted cleaning professionals in your area, making it easy to find the right service for your home or office.</p>
                <p>Use the navigation links to explore our services and manage your bookings.</p>

                    <a href="/providers">Search services</a> 

                <img src="images/cleaning.jpg" alt="cleaning" class="imgintro">

            </div>

            <hr>

                
        
              <footer>
                <p>CSC340 CleanSweep Project</p>
         </footer>
</body>
</html>